### ISSUE TITLE
Assemble script cleanup source

### ISSUE THREAD

**Issue by spinolacastro** [sclorg/s2i-php-container#106]
Hello, i realized that images builded by sti has a considerable size, looking for a answer i've found the source pulled from a git repository is located twice on the output image, once at `/opt/app-root/src` and  `/tmp/src`.

Am i missing something or we can add `rm -rf /tmp/src` at the bottom of assemble script?

**Comment by bparees** [comment]
you can, or you can change the assemble script to do mv instead of cp, this has been discussed here as well:
https://github.com/sclorg/s2i-python-container/issues/84

as you can see there, there are some subtleties to it, as discussed here:
https://github.com/sclorg/s2i-python-container/issues/84#issuecomment-224471693

i'd be open to a PR to the assemble script though, that used a mv instead of cp.

**Comment by bparees** [comment]
assigning myself for now to keep this on my radar, but if you're interested in doing the PR let me know.
