### ISSUE TITLE
/opt/rh/httpd24/root/var/run/httpd/: Permission denied (centos/php-56-centos7)

### ISSUE THREAD

**Issue by andrewklau** [sclorg/s2i-php-container#112]
The dockerhub image centos/php-56-centos7:latest doesn't seem to have the correct permissions set:

`ls cannot open directory /opt/rh/httpd24/root/var/run/httpd/: Permission denied`

openshift/php-55-centos7 does not have this issue

**Comment by andrewklau** [comment]
Sorry it seems I ran the check on openshift/php56-centos7 whish is deprecated.

The permission denied is happening on both openshift/php-55-centos7 and centos/php-56-centos7

**Comment by bparees** [comment]
Wait is it happening on centos/php-56-centos7 or not? Because that one
should be current and working.   (as should openshift/php-55-centos7, but
not 56 as you noted.)

Ben Parees | OpenShift
On Jul 4, 2016 2:10 AM, "Andrew Lau" <notifications@github.com> wrote:

Sorry it seems I ran the check on openshift/php56-centos7 whish is
deprecated.

The permission denied is happening on both openshift/php-55-centos7 and
centos/php-56-centos7

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sclorg/s2i-php-container/issues/112#issuecomment-230212484>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEvl3rN1y_x97sLP9EYz749OHpL2Y1i4ks5qSKPngaJpZM4JEEsw>
.

**Comment by andrewklau** [comment]
I accidentally span up a Ubuntu instance to run the docker build which ended up with those weird results. Back to Fedora and no issues, not sure why that happens though.

To add some context, I was using these images as a FROM for an expansion image.

**Comment by rurikhero** [comment]
i use ubuntu and i have corrected this changing the stored driver to **overlay2** on docker:
**make a file:** 
`
touch /etc/docker/daemon.json
`
**paste the code**
`
{
     "storage-driver": "overlay2"
}
`
**and restart the service**
`
sudo systemctl stop docker
sudo systemctl start docker
`

_ubuntu 16.04
docker 1.13_
