### ISSUE TITLE
JSON access and error log

### ISSUE THREAD

**Issue by philhug** [sclorg/s2i-php-container#154]
I implemented JSON logging in our forked php container.
This has the advantage that the fields of the log are nicely presented in kibana.
Would this be of general interest? If yes, I can prepare a pull request.

**Comment by remicollet** [comment]
Looks like a very specific change (I don"t even know what kibana is, before searching about it)

**Comment by philhug** [comment]
kibana is the app used by openshift's aggregated logging:
https://docs.openshift.com/enterprise/3.2/install_config/aggregate_logging.html

if only a minority of openshift users use it, we should keep those patches separate.

**Comment by nsams** [comment]
That would be useful for anyone using aggregated logging. Please consider integrating that.

**Comment by hhorak** [comment]
Thank you for taking the time to report this issue to us. We appreciate the feedback and use reports such as this one to guide our efforts at improving our products. That being said, we have been not able to get to this issue for a long time, so rather closing it to make it clear we don't see it be addressed soon.

If this issue is critical or in any way time sensitive, please raise a ticket through the regular Red Hat support channels to ensure it receives the proper attention and prioritization to assure a timely resolution.
 
For information on how to contact the Red Hat production support team, please visit: https://access.redhat.com/support
