### ISSUE TITLE
Feature request - add xdebug.max_nesting_level as php.ini env var

### ISSUE THREAD

**Issue by magick93** [sclorg/s2i-php-container#155]
Hello

It would be good if we can set the `xdebug.max_nesting_level` value as an environment variable.

**Comment by phracek** [comment]
xdebug is not installed in our images.

Thank you for taking the time to report this issue to us. We appreciate the feedback and use reports such as this one to guide our efforts at improving our products. That being said, we have been not able to get to this issue for a long time, so rather closing it to make it clear we don't see it be addressed soon.

If this issue is critical or in any way time sensitive, please raise a ticket through the regular Red Hat support channels to ensure it receives the proper attention and prioritization to assure a timely resolution.

For information on how to contact the Red Hat production support team, please visit: https://access.redhat.com/support
