### ISSUE TITLE
Install PEAR package

### ISSUE THREAD

**Issue by mkosek** [sclorg/s2i-php-container#180]
With OpenShift v2, there was an easy way to install PEAR dependency in PHP cartridge, by editing `.openshift/pear.txt`.

Is there something similar with this s2i container? I see that PEAR is mentioned in include path (`/opt/rh/rh-php70/root/usr/share/pear`), but I am not sure how to install a dependency there.

**Comment by hhorak** [comment]
The `composer.json` file is used for this, see an example: https://github.com/sclorg/s2i-php-container/blob/master/7.1/test/test-app/composer.json
@remicollet is there a different way?

**Comment by remicollet** [comment]
All pear packages may be installed using the "pear install ..." command

But, some pear packages can be installed using the composer way

```
    "require": {
        "php": "^5.3 || ^7",
        "pear-pear.php.net/Net_Socket": "*"
    ...

```

**Comment by phracek** [comment]
Thank you for taking the time to report this issue to us. We appreciate the feedback and use reports such as this one to guide our efforts at improving our products. That being said, we have been not able to get to this issue for a long time, so rather closing it to make it clear we don't see it be addressed soon.

If this issue is critical or in any way time sensitive, please raise a ticket through the regular Red Hat support channels to ensure it receives the proper attention and prioritization to assure a timely resolution.

For information on how to contact the Red Hat production support team, please visit: https://access.redhat.com/support
