### ISSUE TITLE
/tmp/sessions permission denied

### ISSUE THREAD

**Issue by slbteam08** [sclorg/s2i-php-container#189]
I pulled the latest centos/php-71-centos7 and found my apps start showing permission denied errors on /tmp/session/:

`Warning: session_start(): open(/tmp/sessions/sess_eb242dea5a72c0892fa8758d86836ec0, O_RDWR) failed: Permission denied (13)
`

I looked that code and found that seems caused by a recent change which introduced the /usr/libexec/container-setup script. In this script /tmp/sessions owner is set to 1000:0. It used to be 1001:0.

Sorry that I am not familiar with steps to contribute code change. Could anyone help fixing the issue?

**Comment by omron93** [comment]
@slbteam08 Thanks for reporting this problem. Contribution is welcomed - simply create a PR. One basic rule is that we try to keep supported versions similar as possible (to keep maintenance simpler) - https://github.com/sclorg/welcome/blob/master/contribution.md#active-versions. So please do changes in all version listed in `VERSIONS` in https://github.com/sclorg/s2i-php-container/blob/master/Makefile

@hhorak Was setting user `1000` for `/tmp/sessions` intentional?

**Comment by hhorak** [comment]
> @hhorak Was setting user 1000 for /tmp/sessions intentional?

It was definitely not intentional O:-) Thanks both for spotting and analysis. PR for fixing this prepared: #191.

**Comment by omron93** [comment]
@slbteam08 Should be fixed. If the problem still persist please reopen the issue.

**Comment by slbteam08** [comment]
@omron93 I tested with the updated image and saw the owner changed, but still getting "permission denied" errors. Maybe "chmod a+rwx /tmp/sessions" is needed as well?

**Comment by omron93** [comment]
Again. @slbteam08 This should be fixed. If the problem still persist please reopen the issue.
