### ISSUE TITLE
Potential security improvement suggestion

### ISSUE THREAD

**Issue by xrow** [sclorg/s2i-php-container#232]
We were lookig at this line

https://github.com/sclorg/s2i-php-container/blob/master/7.1/Dockerfile#L76

The resulting permissions inside the container are

```[root@localhost src]# docker exec -it httpd bash
bash-4.2$ id
uid=1001(default) gid=0(root) groups=0(root)
bash-4.2$ 
```

We were wondering if it would be good to also set a proper group like apache or else instead of root group.

**Comment by omron93** [comment]
@xrow Thanks for pointing this out.

But this is intentional to support usage in OpenShift. It runs containers with "a random user ID"[1] and `root` group. So `root` group is used to assure write permissions to files/directories where needed.

More information also in this blog post [2].

[1] https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html
[2] https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/

**Comment by xrow** [comment]
Hi,

I understand and it makes sense. We don`t know then yet why the userid is preset to 1001, but that doesn`t matter much. Please close.

**Comment by omron93** [comment]
>  We dont know then yet why the userid is preset to 1001, but that doesnt matter much.

Agree. Same user is used for all language images (php, perl, python,...) so it's hard to choose right. There is a TODO[1] about this for some time:-) but I agree that it doesn't matter much. Suggestions are welcomed.

[1] https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile#L42
