### ISSUE TITLE
Feature-Request: Add ODO support

### ISSUE THREAD

**Issue by mchauvel** [sclorg/s2i-php-container#267]
Hi, 

Do you plan to add ODO support in PHP images ?

```
> odo catalog list components
Odo Unsupported OpenShift Components:
NAME     PROJECT       TAGS
php      openshift     5.5,5.6,7.0,7.1,7.2,latest
```

**Comment by pkubatrh** [comment]
Hi @mchauvel 

What "support" do you expect here?
All of our php images are able to be run on an Openshift cluster. They are officially supported by Red Hat when run on top of RH OCP, but have community support when run on OKD (could be what "unsupported" means here?).
I have to admit I have yet to try out using `odo` instead of `oc` but afaik `odo` is just a different way of interacting with the cluster, so I would not expect there to be a need for specific "odo support" in the image to make it work.

**Comment by mchauvel** [comment]
I already use `odo` with php 7.2 image and it works well, except the `odo watch` comand that is a bit long (~8s for each change).
After i read this [odo doc page](https://github.com/openshift/odo/wiki/How-s2i-builder-images-are-used), i was not sure that the `assemble` script in the php images is optimized for better `odo` support with `odo watch` comand.

What i'm looking for, is a way to instantly detect change of my source file and sync it in my pod.

Thanks.
Max

**Comment by pkubatrh** [comment]
From: https://github.com/openshift/odo/issues/2289#issuecomment-542625188


>Sadly we can't currently guaranteed that odo will work with any s2i builder image. This is why we recently started grouping images into supported, and unsupported. Supported are those that we test and we make sure that it works (currently nodejs, and java (openjdk based)), the unsupported might work, or might break, it depends how image was built.


So it seems like if you want to have php image supported by odo, you should create an issue against openshift/odo to make sure the php images are tested to be guaranteed to work.

Regarding the `assemble` script and `odo watch` - if I understand it correctly then there might be some slow down during container respin by a change in sources as the sources are moved and not copied into `/opt/app-root/`. We are actually thinking about unifying the operation right now (`cp` vs `mv`) for all of our images` `assemble` scripts so if you think this would make a difference for the php image - please, try it out and let us know!
PRs are also always appreciated.
