### ISSUE TITLE
centos/php-73-centos7 missing on docker hub

### ISSUE THREAD

**Issue by xrow** [sclorg/s2i-php-container#277]
Hi,

I noticed the image centos/php-73-centos7 is missing on docker hub. Did one forget it?

**Comment by pkubatrh** [comment]
Hi @xrow 

only ubi8-based image was added in https://github.com/sclorg/s2i-php-container/pull/261. The centos7-based image for php 7.3 is not being built yet, which is why it is missing from dockerhub.

I will follow up with a PR to try and enable rhel7/centos7 builds to see if any more changes are needed for them.
