### ISSUE TITLE
php-pecl-zip package still not added to rhel-8 containers on registry.redhat.io

### ISSUE THREAD

**Issue by gripenk** [sclorg/s2i-php-container#341]
Although #331 is merged, the images hosted on registry.redhat.io : 
registry.redhat.io/ubi8/php-74:latest
registry.access.redhat.com/ubi8/php-74:latest

do not include php-pecl-zip yet

**Comment by gripenk** [comment]
it finally included in 1-42: 
registry.access.redhat.com/ubi8/php-74@sha256:aee9110f21c85f42987cb358c541628ec19caafea8ea4599067855293dbc1721

**Comment by pkubatrh** [comment]
Note that the RHEL-based images are not getting updated with every PR being merged upstream, only with every single minor release of RHEL (eg. 8.5 recently).
In case you have a need of some specific feature available in upstream repositories but not yet available in RHEL-based images it is better to open a customer ticket with Red Hat Support so that the request is properly tracked.
