### ISSUE TITLE
PHP 8.1 build - It's the latest/greatest/fastest and we're anxious to start using it.

### ISSUE THREAD

**Issue by olstjos** [sclorg/s2i-php-container#374]
Locally I've tested my code using wodby on PHP 8.1 and 8.0, having a bit of trouble getting the s2i working in openshift/red hat for PHP 8.0, with that said, I'd much rather spend all this time getting PHP 8.1 going, any chance that PHP 8.1 builds will be ready soon?  There's additional performance improvements and reduced memory footprint available by using the latest and greatest PHP.

https://kinsta.com/blog/php-benchmarks/

**Comment by pkubatrh** [comment]
Hi there @olstjos,
seems like the first module builds for PHP 8.1 are hitting Centos Stream 9 so we will be able to start working on the c9s version of the image quite soon. So if you are okay with using Centos Stream images, be on the lookout for the new image.

**Comment by joejoseph00** [comment]
Hello @pkubatrh  I've got PHP 8.2.1 up and running with Ubuntu and it's blazingly fast, takes even less memory than PHP 8.1.

We need to get at least PHP 8.1 going here with the s2i-php-container because we're trying to run hundreds of pods on razor thin resources and we need to squeeze every single byte of ram and every cpu cycle to the maximum.  Our cloud billing is huge, our apps need to be faster and we need to get PHP 8.1 going asap.  PHP 8.0 will be end of life this year so we need to at least get started on PHP 8.1.

We're not running a bank with custom software, we are running cutting edge publicly available open source software and we need to stay current with security advisory releases and be ready for upgrades and everything the world is throwing at us.  Every extra bit of performance is improved availability and allows us to deal better with bots and concurrency and keep latency low.

**Comment by pkubatrh** [comment]
Hi @joejoseph00 
PHP 8.1 has been available on RHEL9 for a good while, feel free to give it a try: https://catalog.redhat.com/software/containers/ubi9/php-81/62e8e662f6d3d47e19779b01

**Comment by joejoseph00** [comment]
Hi @pkubatrh  thanks so much for looking into this.  
PHP 8.0 will become EOL on november 26th 2023, and we often start developing on beta releases that are scheduled to be released a week or two AFTER the EOL date.  As developers we need to be as far ahead of EOL as possible so that we can achieve our deliverables on time.  On november 26th 2023 we will lose access to upgrades of older version dependencies that we need to keep our application secure and long before this EOL date we also lose access to new functionality of the open source dependencies we rely on unless we develop using other platforms outside of the RHEL space.

Extended support option of out of support versions of PHP is not an ideal option for us because 
1) Newer versions of PHP consume less memory than older versions
2) Newer versions of PHP provide significant performance improvements than older versions
3) Newer versions of PHP are required by updated dependencies
4) Security updates of dependencies require Zend supported versions of PHP
5) We need to develop new releases prior to deploying them so developers need to stay ahead of the curve.

**Comment by pkubatrh** [comment]
PHP 8.1 should have been available in winter 2022, but there was an issue with how the image was being built, so it still has PHP 8.0 inside, not 8.1 as expected. This should be fixed in the coming weeks. So yes, definitely before May 2023.

**Comment by olstjos** [comment]
@pkubatrh Hi Petr, I got wind from Andrew of Red Hat that they fixed the glitch, does this mean we're almost ready to get the PHP 8.1 added to the s2i-php-container ?

**Comment by joejoseph00** [comment]
Wow great to see this get done, looking forward to it!  We'll test it out once it's merged.

**Comment by olstjos** [comment]
Thank you @phracek  and @pkubatrh for resolving this, I will test this out soon I hope.

**Comment by joejoseph00** [comment]
PHP 8.1 is old news , PHP 8.3 is 53% faster on Drupal than compared with PHP 8.1 and Kinstas benchmarking.
https://github.com/sclorg/s2i-php-container/issues/435
