### ISSUE TITLE
The environment variables are not available for PHP

### ISSUE THREAD

**Issue by mfojtik** [sclorg/s2i-php-container#83]
I think this problem existed in v2 as well. The environment variables has to be listed in the appropriate config in Apache, otherwise PHP won't be able to see them.

**Comment by mfojtik** [comment]
@remicollet FYI (I think we will have to generate the `SetEnv` directives based on the env vars available in container)

**Comment by mfojtik** [comment]
fyi i think I have fix for this, stay tuned

**Comment by sjenning** [comment]
So this is still a thing I hit it today.

In the 5.6 sti builder, the produced image does not populate `$_ENV` where the image the 5.5 sti builder does.

This is why:
https://github.com/sclorg/s2i-php-container/blob/master/5.6/contrib/etc/php.ini.template#L612
https://github.com/sclorg/s2i-php-container/blob/master/5.5/contrib/etc/php.ini.template#L669

The 5.6 `variables_order` in `php.ini` does not include "E", which populates the $_ENV array.

This can be worked around by using `getenv()` instead of `$_ENV`.
